### ISSUE TITLE
Make labour force 2 words in title

### ISSUE THREAD

**Issue by Henry-DJPR** [djsir-data/djprlabourdash#222]
It's currently one

**Comment by Henry-DJPR** [comment]
Also in email

**Comment by Henry-DJPR** [comment]
@annett-djpr would you be abl to fix these up? Just got a request from Bonnie

**Comment by annett-djpr** [comment]
Yes, no problem.

**Comment by mrjoh3** [comment]
fixed with 977c56d9b23138f86a57fd9d1df80d6fc6a6309d
